name: codeway_flutter_case
description: ImageFlow - Codeway Flutter case study POC.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.8 <4.0.0"
  flutter: ">=3.38.4"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  google_mlkit_face_detection: ^0.13.2
  google_mlkit_text_recognition: ^0.15.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.5.4
  image_picker: ^1.2.1
  open_filex: ^4.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
